{{- if .Values.firstInstall -}}
kind: Secret
apiVersion: v1
metadata:
  name: courie-web-directions-api-key
data:
  REACT_APP_DIRECTIONS_KEY: {{ b64enc .Values.directionsApiKey }}
type: Opaque
{{- end }}